AWSTemplateFormatVersion: 2010-09-09
Description: Kgothatso Thema | Infrastructure Creation

Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        SecurityGroups:
          - !Ref InstanceSecurityGroup
        KeyName: des-the-dev
        ImageId: 'ami-0cff7528ff583bf9a'
        InstanceType: t3.micro
  
    InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable SSH access via port 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0 